name:                cube-tree
version:             0.1.0.0
github:              "githubuser/cube-tree"
license:             BSD3
author:              "Miksu Rankaviita"
maintainer:          ""
copyright:           "2023 Miksu Rankaviita"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MiksuR/cube-tree#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- array >= 0.5.4
- text-format-simple >= 1.1
- combinat >= 0.2.10.0
- random >= 1.1
- extra >= 1.7.13

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cube-tree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cube-tree

tests:
  cube-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cube-tree
